In [1]:
import numpy as np
a = [0,1,2,3,4,5]
res = np.array(a)
res, res.dtype

(array([0, 1, 2, 3, 4, 5]), dtype('int32'))

In [2]:
a2 = [10,9,8,7.5,6.5]
res2 = np.array(a2)
res2, res2.dtype

(array([10. ,  9. ,  8. ,  7.5,  6.5]), dtype('float64'))

In [3]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [5]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.arange(9).reshape(3,3).shape

(3, 3)

In [8]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.array(['1.0', '2.1', '3.2', '4.12', '5'])

array(['1.0', '2.1', '3.2', '4.12', '5'], dtype='<U4')

In [15]:
a = np.array(['1.0', '2.1', '3.2', '4.12', '5'])
a1 = a.astype(float)
a1

array([1.  , 2.1 , 3.2 , 4.12, 5.  ])

In [16]:
a1.dtype

dtype('float64')

In [17]:
np.random.rand(3,4)

array([[0.41293252, 0.89310301, 0.83786382, 0.52679235],
       [0.84748376, 0.88418102, 0.38192763, 0.74184862],
       [0.12235953, 0.90884372, 0.10111149, 0.01352339]])

In [18]:
np.random.rand(2,3,4)

array([[[0.44720246, 0.77841294, 0.42237679, 0.86277678],
        [0.67919754, 0.40349469, 0.02662859, 0.1584762 ],
        [0.63188856, 0.71647059, 0.90475159, 0.40489714]],

       [[0.99779965, 0.30707352, 0.88644827, 0.31561886],
        [0.46067433, 0.72396799, 0.13460749, 0.11662575],
        [0.79504003, 0.47126038, 0.16071965, 0.84431838]]])

In [19]:
np.random.randint(1,10)

5

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [21]:
print(a+b)
print(a-b)
print(a*b)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [22]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [23]:
a>4

array([False, False, False, False,  True])

In [24]:
a.sum()

15

In [25]:
a.mean()

3.0

In [26]:
a.std()

1.4142135623730951

In [27]:
a.var()

2.0

In [28]:
a.max()

5

In [29]:
a.cumsum()

array([ 1,  3,  6, 10, 15])

In [30]:
a.cumprod()

array([  1,   2,   6,  24, 120])

In [31]:
A = np.array([1,2,3,4]).reshape(2,2)
B = np.array([3,4,5,6]).reshape(2,2)
print(A)
print(B)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]


In [32]:
np.dot(A,B)

array([[13, 16],
       [29, 36]])

In [33]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

In [34]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [35]:
np.linalg.det(A)

-2.0000000000000004

In [36]:
z = np.array([0,1,2,3,4,5,5,6,7,8,9])

In [37]:
print(z[1])
print(z[1:6])
print(z[:5])
print(z[[1,4,2,6]])

1
[1 2 3 4 5]
[0 1 2 3 4]
[1 4 2 5]


In [38]:
z1 = np.array([[1,2,3],
               [3,4,5],
               [6,7,8]])
z1

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [39]:
z1[0,2]

3

In [40]:
z1[1]

array([3, 4, 5])

In [41]:
z1[1] = [10,20,30]
z1

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 6,  7,  8]])